spring:
  config:
    activate:
      on-profile: local
    import: optional:configserver:http://127.0.0.1:8888
  # rabbitmq settings
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/member-service
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    # Bean이 생성되기 전에 ddl 실행
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG